import {
  pgTable,
  text,
  serial,
  timestamp,
  boolean,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Claims Ledger — the truth-lock source of truth.
 *
 * A claim is a single verified factual unit about the user: a skill usage,
 * project outcome, metric, responsibility, or achievement. Every resume bullet
 * generated by the AI must trace back to one or more claims. The AI is given
 * a list of claim IDs and instructed to cite them; any bullet that cites a
 * non-existent claim ID is discarded by the validation layer.
 *
 * Inactive claims (`isActive = false`) are excluded from pipeline matching but
 * remain in the database for audit purposes.
 */
export const claimsTable = pgTable(
  "claims",
  {
    /** Auto-incrementing primary key. */
    id: serial("id").primaryKey(),

    /** Canonical statement of the claim (e.g. "Led migration of monolith to microservices, reducing P99 latency by 40%"). */
    summary: text("summary").notNull(),

    /** Source of truth: a URL, document reference, or self-attestation text. */
    evidence: text("evidence"),

    /** How the evidence was obtained. Values: `self_attestation`, `document`, `url`. */
    evidenceType: text("evidence_type").notNull().default("self_attestation"),

    /** Alternative phrasings the AI may use when generating bullets from this claim. */
    phrasingVariants: text("phrasing_variants").array().notNull().default([]),

    /** Implications this claim must NEVER make (e.g. "sole contributor" when it was a team effort). */
    disallowedImplications: text("disallowed_implications")
      .array()
      .notNull()
      .default([]),

    /** Professional domain (e.g. `backend`, `ml`, `leadership`). Used for filtering in the dashboard. */
    domain: text("domain"),

    /** Tags for matching against job requirements (e.g. `["typescript", "react", "team-lead"]`). */
    applicableTags: text("applicable_tags").array().notNull().default([]),

    /** Whether this claim is included in pipeline matching. Defaults to true. */
    isActive: boolean("is_active").notNull().default(true),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("claims_domain_active_idx").on(table.domain, table.isActive),
    index("claims_active_idx").on(table.isActive),
  ],
);

/** Zod schema for inserting a claim (omits server-managed fields). */
export const insertClaimSchema = createInsertSchema(claimsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

/** Type for a new claim insert payload. */
export type InsertClaim = z.infer<typeof insertClaimSchema>;

/** Type for a full claim row as returned from the database. */
export type Claim = typeof claimsTable.$inferSelect;
