import {
  pgTable,
  text,
  serial,
  timestamp,
  integer,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { jobsTable } from "./jobs";

/**
 * Cover letter versions — AI-drafted cover letters awaiting human approval.
 *
 * Generated by the cover letter pipeline. Each version contains the full draft text
 * and paragraph-level claim attribution (`annotatedParagraphs`). The user reviews
 * claim attribution in the dashboard and either approves the letter or requests a
 * revision (the revision note is stored in `notes` before rejection).
 *
 * Paragraph roles: `opening`, `hook`, `body`, `closing`
 * - `body` and `hook` paragraphs must cite at least one valid claim ID (truth lock).
 * - `opening` and `closing` paragraphs may be unattributed (salutation/sign-off).
 *
 * State machine: `pending_approval` → `approved` | `rejected`
 * Any attempt to approve/reject from a non-`pending_approval` state returns HTTP 409.
 */
export const coverLetterVersionsTable = pgTable(
  "cover_letter_versions",
  {
    /** Auto-incrementing primary key. */
    id: serial("id").primaryKey(),

    /** The job this cover letter was drafted for. Cascade-deletes the version if the job is deleted. */
    jobId: integer("job_id").references(() => jobsTable.id, {
      onDelete: "cascade",
    }),

    /** Human-readable label (e.g. "AI drafted — Jun 15, 2025"). Auto-set by the pipeline. */
    label: text("label"),

    /**
     * Current state. `pending_approval` until the user acts.
     * Values: `pending_approval`, `approved`, `rejected`
     */
    status: text("status").notNull().default("pending_approval"),

    /** Full plain-text cover letter draft (used when `annotatedParagraphs` is not available). */
    draftContent: text("draft_content"),

    /**
     * Array of annotated paragraph objects.
     * Each entry shape: `{ text: string, claimIds: number[], role: "opening" | "hook" | "body" | "closing" }`
     * All claimIds are validated against the Claims Ledger before storage.
     */
    annotatedParagraphs: jsonb("annotated_paragraphs").notNull().default([]),

    /** Flat list of all claim IDs referenced across all paragraphs. */
    claimIds: integer("claim_ids").array().notNull().default([]),

    /**
     * User or system notes. When the user requests a revision via the dashboard,
     * the revision rationale is stored here before the version is rejected,
     * providing a traceable record of why the draft was rejected.
     */
    notes: text("notes"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("cover_letter_versions_job_id_idx").on(table.jobId),
    index("cover_letter_versions_status_idx").on(table.status),
  ],
);

/** Zod schema for inserting a cover letter version (omits server-managed fields). */
export const insertCoverLetterVersionSchema = createInsertSchema(
  coverLetterVersionsTable,
).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

/** Type for a new cover letter version insert payload. */
export type InsertCoverLetterVersion = z.infer<
  typeof insertCoverLetterVersionSchema
>;

/** Type for a full cover letter version row as returned from the database. */
export type CoverLetterVersion = typeof coverLetterVersionsTable.$inferSelect;
