import { integer, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

import { conversations } from "./conversations";

/**
 * Messages — individual turns within a conversation.
 *
 * Each message belongs to a `conversations` row and records a single turn
 * in the exchange: either a user prompt or an AI response.
 *
 * `role` values follow the OpenAI/OpenRouter convention:
 * - `"user"` — a message sent by the human user
 * - `"assistant"` — a response generated by the AI model
 * - `"system"` — a system-injected instruction (e.g. context injection)
 *
 * Messages are cascade-deleted when their parent conversation is deleted.
 */
export const messages = pgTable("messages", {
  /** Auto-incrementing primary key. */
  id: serial("id").primaryKey(),

  /** The conversation this message belongs to. Cascade-deletes if the conversation is deleted. */
  conversationId: integer("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),

  /**
   * The sender role. Follows OpenAI message role convention.
   * Values: `"user"`, `"assistant"`, `"system"`
   */
  role: text("role").notNull(),

  /** The text content of the message. */
  content: text("content").notNull(),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/** Zod schema for inserting a message (omits server-managed fields). */
export const insertMessageSchema = createInsertSchema(messages).omit({
  id: true,
  createdAt: true,
});

/** Type for a full message row as returned from the database. */
export type Message = typeof messages.$inferSelect;

/** Type for a new message insert payload. */
export type InsertMessage = z.infer<typeof insertMessageSchema>;
